name: begd
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

license:
  - GPL-3.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_bloc: ^9.1.1
  flutter_launcher_icons: ^0.14.3
  flutter_screenutil: ^5.9.3
  image_picker: ^1.1.2
  package_info_plus: ^8.3.0
  smooth_page_indicator: ^1.2.1
  toastification: ^3.0.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  equatable: ^2.0.7
  shared_preferences: ^2.5.3
    

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo/static/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Cairo/static/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/Cairo/static/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/Cairo/static/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/Cairo/static/Cairo-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Cairo/static/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo/static/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Cairo/static/Cairo-Black.ttf
          weight: 900

